version: "3.9"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-init:
    image: mysql
    command: sh -c 'sleep 10 && mysql -h db -uroot -ppassword < /init.sql'
    volumes:
      - ./database/init.sql:/init.sql
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379:6379"
